version: '3.4'

services:
  csvuploader.api:
    image: ${DOCKER_REGISTRY-}csvuploaderapi
    build:
      context: .
      dockerfile: CsvUploader.Api/Dockerfile

  csvuploader.rabbitmq:
    image: rabbitmq:3.7.2-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mydata: